// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';

// ...

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCglu_vJRUi9UTdUf-0omniNAHxitaU4Ak',
    appId: '1:837225717237:android:601bb97a211613cbd8d4bc',
    messagingSenderId: '837225717237',
    projectId: 'mypfe-9a4cd',
    databaseURL: 'https://mypfe-9a4cd-default-rtdb.firebaseio.com',
    storageBucket: 'mypfe-9a4cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDItpQ8_EgXcl_KQtjgmwMFCjfXeMv1ZbU',
    appId: '1:837225717237:ios:b2e60c9ccfc38ae7d8d4bc',
    messagingSenderId: '837225717237',
    projectId: 'mypfe-9a4cd',
    databaseURL: 'https://mypfe-9a4cd-default-rtdb.firebaseio.com',
    storageBucket: 'mypfe-9a4cd.firebasestorage.app',
    iosBundleId: 'com.example.hadarni',
  );
}
